### PR TITLE
Feature/transition names

### PR DESCRIPTION
**Pull request by alorma**
I made a small PR in order to solve: https://github.com/SchibstedSpain/Leku/issues/30

### CODE REVIEW

**Comment by ferranpons** [comment]
@alorma What could we do with this? Worth finishing it or do we close it?

**Comment by alorma** [comment]
i will fix the conflicts and update the PR.

**Comment by ferranpons** [comment]
Cool! Thanks! (priority low you know 😉 )

**Comment by ferranpons** [comment]
@alorma remember to update the Readme if the users need to make something to enable the transition animations on their side. Many thanks!

**Pull request closed without merging**
