### PR TITLE
Update sdk 26

### PR DESCRIPTION
**Pull request by alorma**
As requested by @ruha9005, update api version to 26

https://github.com/SchibstedSpain/Leku/issues/99

### CODE REVIEW

**Comment by ruha9005** [comment]
Supprot libs also need to be updated.
For examle:
`compile 'com.android.support:appcompat-v7:26.0.+'`

**Comment by alorma** [comment]
Afaik @ruha9005 , support 26+ is still on beta, right?

**Comment by ruha9005** [comment]
@alorma It's in alpha. They needed for sdk 26 compatibility. But I can be wrong.

**Comment by sagarikadas91** [comment]
It is not working for android 26+ version

**Comment by ferranpons** [comment]
@sagarikadas91 the PR #117 is where is being upgraded to api 26. I close this PR.

**Pull request closed without merging**
