### PR TITLE
Point map on user location after accept permission

### PR DESCRIPTION
**Pull request by alorma**
This PR fixes issue #24 opened by @rocboronat.

I've added an option to get `LastKnowLocation`once user accepts the permission. I'm not sure if it should get last location, or ask for location update

### CODE REVIEW

**Comment by rocboronat** [comment]
Thanks for that **quick** fix!

**Comment by alorma** [comment]
Done with that @rocboronat

**Comment by rocboronat** [comment]
Thanks @alorma ! You have my lovely finger 💋  👍

**Comment by ferranpons** [comment]
👍

**Pull request merged**
