### PR TITLE
Update Leku README with AndroidReactiveLocation patch

### PR DESCRIPTION
**Pull request by alorma**
With this, we show at Readme that developers should add SchibstedSpain maven repository in their `build.gradle` files

### CODE REVIEW

**Comment by gerardpedrenyscmspain** [comment]
👍

**Comment by rocboronat** [comment]
Squash the commits before merging, please! :-)

**Comment by CristianGM** [comment]
Not needed anymore
It's on JCenter 😃

**Comment by ferranpons** [comment]
@alorma please update this branch with the recent changes including the jcenter change. Right now the readme in master is outdated. It shows version 2.0.0 when it's available the 2.0.1.

annoyed

**Comment by alorma** [comment]
Done @ferranpons

**Comment by ferranpons** [comment]
:+1: thanks @alorma !

nice

**Pull request merged**
