### PR TITLE
Now FABs follow Theme colours

### PR DESCRIPTION
**Pull request by ferranpons**
Solves issue #42

### CODE REVIEW

**Comment by alorma** [comment]
Instead of use `?colorPrimary` why not use custom attr? Like `?lekuPrimaryFab`?

So themes could be more rich, instead of single color

**Comment by ferranpons** [comment]
I don't think that it's necessary a custom attribute because you could achieve the same level of customization adding new themes to your styles. For example:

```
  <style name="AppTheme"
         parent="Theme.AppCompat.Light.NoActionBar">
    <item name="colorPrimary">#009688</item>
    <item name="colorPrimaryDark">#00695C</item>
    <item name="colorAccent">#2979FF</item>
  </style>

  <style name="AppTheme.Map">
    <item name="colorPrimary">#E91E63</item>
    <item name="colorPrimaryDark">#C51162</item>
    <item name="colorAccent">#FBC02D</item>
    <item name="colorControlActivated">#E91E63</item>
  </style>
```

**Comment by alorma** [comment]
mmmm, ok well, leku activity doesn´t have toolbar, so it's ok

**Comment by marcserrascmspain** [comment]
👍

**Comment by iamdeadman** [comment]
Hi, 

I am facing similar issue here. Tried searching the source code for the fab background and ripple tint attributes, but it seems they have been moved to `@color/leku_white` and `@color/leku_soft_grey` 

I think the attribute approach was easier for customizing the fab theme. Now, how can this be done with the existing version of this library ?

**Pull request merged**
